services:
  nuxt:
    build: .
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    working_dir: /app
    command: npm run dev
    environment:
      - NODE_ENV=development
